#!/usr/bin/env fish
# Fish shell secure secrets setup for Cribbage app signing

echo "=== Cribbage App Signing - Secure Secrets Setup ==="
echo ""
echo "This will create a separate secrets file NOT committed to git."
echo ""

set secrets_file ~/.config/fish/secrets.fish

# Get keystore password
read -sP "Enter keystore password: " keystore_password
echo ""

# Get key password (can be same as keystore password)
read -sP "Enter key password (press Enter if same as keystore): " key_password
echo ""

# If key password is empty, use keystore password
if test -z "$key_password"
    set key_password $keystore_password
end

# Create secrets file
echo "# Cribbage App Signing Secrets" > $secrets_file
echo "# DO NOT COMMIT THIS FILE TO GIT!" >> $secrets_file
echo "# Generated by setup_fish_secrets.fish on "(date) >> $secrets_file
echo "" >> $secrets_file
echo "set -gx CRIBBAGE_KEYSTORE_PASSWORD \"$keystore_password\"" >> $secrets_file
echo "set -gx CRIBBAGE_KEY_PASSWORD \"$key_password\"" >> $secrets_file

# Set restrictive permissions
chmod 600 $secrets_file

echo "✅ Created secure secrets file: $secrets_file"
echo "✅ Set permissions to 600 (owner read/write only)"
echo ""

# Add to config.fish if not already there
if not grep -q "source ~/.config/fish/secrets.fish" ~/.config/fish/config.fish
    echo "" >> ~/.config/fish/config.fish
    echo "# Cribbage App Signing Configuration" >> ~/.config/fish/config.fish
    echo "set -gx CRIBBAGE_KEYSTORE_PATH \"\$HOME/.android/keystores/cribbage-release-key.jks\"" >> ~/.config/fish/config.fish
    echo "set -gx CRIBBAGE_KEY_ALIAS \"cribbage-release\"" >> ~/.config/fish/config.fish
    echo "" >> ~/.config/fish/config.fish
    echo "# Source secrets file (not in git)" >> ~/.config/fish/config.fish
    echo "if test -f ~/.config/fish/secrets.fish" >> ~/.config/fish/config.fish
    echo "    source ~/.config/fish/secrets.fish" >> ~/.config/fish/config.fish
    echo "end" >> ~/.config/fish/config.fish

    echo "✅ Added configuration to ~/.config/fish/config.fish"
else
    echo "ℹ️  Configuration already exists in config.fish"
end

# Check if .gitignore exists in Fish config dir
if test -f ~/.config/fish/.gitignore
    if not grep -q "secrets.fish" ~/.config/fish/.gitignore
        echo "secrets.fish" >> ~/.config/fish/.gitignore
        echo "✅ Added secrets.fish to ~/.config/fish/.gitignore"
    else
        echo "ℹ️  secrets.fish already in .gitignore"
    end
else
    echo "secrets.fish" > ~/.config/fish/.gitignore
    echo "✅ Created ~/.config/fish/.gitignore with secrets.fish"
end

echo ""
echo "📋 Variables configured:"
echo "  In config.fish (safe to commit):"
echo "    • CRIBBAGE_KEYSTORE_PATH"
echo "    • CRIBBAGE_KEY_ALIAS"
echo ""
echo "  In secrets.fish (NOT in git):"
echo "    • CRIBBAGE_KEYSTORE_PASSWORD"
echo "    • CRIBBAGE_KEY_PASSWORD"
echo ""
echo "🔐 Security checklist:"
echo "  ✅ Secrets stored in separate file"
echo "  ✅ File permissions set to 600"
echo "  ✅ Added to .gitignore"
echo ""
echo "To apply now, run:"
echo "  source ~/.config/fish/config.fish"
echo ""
echo "Or just open a new terminal window."
