# Podfile for Cribbage iOS App

platform :ios, '14.0'

target 'Cribbage' do
  use_frameworks!

  # Link the shared Kotlin framework
  pod 'shared', :path => '../shared'
end

# Post-install hook to configure build settings
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Disable bitcode (required for Kotlin Native)
      config.build_settings['ENABLE_BITCODE'] = 'NO'

      # Set minimum iOS version
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
